### ISSUE TITLE
Incomplete Install

### ISSUE THREAD

**Issue by sandyl27** [GuyTeichman/RNAlysis#12] opened 2023-02-28 16:27 UTC
I installed rnalysis by following the installation instructions but it didn't install all of the files. 
I am on MacOS Ventura and I am using python 3.9

![Screenshot 2023-02-28 at 10 26 53 AM](https://user-images.githubusercontent.com/12057637/221915572-9be5ed85-893c-4680-b583-09d971218da8.png)

**Comment by GuyTeichman** [comment] 2023-03-01 09:11
Hi,
What command exactly did you use? What feedback did you get after typing the terminal command?

My guess would be that you had a previous version of RNAlysis installed on your system, and you would need to upgrade the existing installation instead of installing a new one.

The command would look like so for the basic version:
`pip install --upgrade RNAlysis`

And like so for the full version:
`pip install --upgrade RNAlysis[all]`

Please let me know if that works.
Best,
Guy.

**Comment by GuyTeichman** [comment] 2023-03-01 21:30
Hi,
could you please post the output of the R script, which appears in the RNAlysis log box at the bottom of you screen?

**Comment by sandyl27** [comment] 2023-03-01 21:35
![Screenshot 2023-03-01 at 3 33 26 PM](https://user-images.githubusercontent.com/12057637/222269780-f16053aa-cf59-48e6-875c-3ad6b52c397f.png)

**Comment by GuyTeichman** [comment] 2023-03-01 22:40
Hi,
Thanks for the bug report. 
I think I figured out what the issue is - there appears to be a problem with pointing RNAlysis to the R script which installs DESeq2. 
The issue should be fixed in the next minor release of RNAlysis (3.6.0), which will be released in a week or two. 

Unfortunately, the only workaround I can suggest in the meantine is to run RNAlysis on a computer with a different operating system (Windows or Linux), or to run your DESeq2 analysis manually through R. 

Thanks and sorry for the inconvenience,
Guy.

**Closed** 2023-03-07 20:08 UTC
